import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  preflight: true,
  include: ['./src/**/*.{ts,tsx}'],
  exclude: [],
  theme: {
    tokens: {
      colors: {
        obsidian: { value: '#1a1a2e' },
        obsidianLight: { value: '#252540' },
        obsidianMid: { value: '#2d2d4a' },
        roseGold: { value: '#c4956a' },
        roseGoldLight: { value: '#d4a97a' },
        roseGoldMuted: { value: '#a07850' },
        warmCream: { value: '#f5f0e8' },
        warmCreamDark: { value: '#e8e0d0' },
        slateBlue: { value: '#6b7fa3' },
        slateBlueDark: { value: '#5a6d8f' },
        slateBlueLight: { value: '#8899b8' },
        success: { value: '#4caf7d' },
        warning: { value: '#e8a948' },
        error: { value: '#d94f4f' },
        info: { value: '#5b9bd5' },
        surfaceDark: { value: '#0f0f1a' },
        surfaceMid: { value: '#1a1a2e' },
        surfaceLight: { value: '#252540' },
        surfaceOverlay: { value: 'rgba(26, 26, 46, 0.95)' },
        textPrimary: { value: '#f5f0e8' },
        textSecondary: { value: '#b0a898' },
        textMuted: { value: '#6b6878' },
        borderDefault: { value: '#2d2d4a' },
        borderFocus: { value: '#c4956a' },
      },
      fonts: {
        heading: { value: "'Playfair Display', serif" },
        body: { value: "'Inter Variable', 'Inter', sans-serif" },
        mono: { value: "'JetBrains Mono', monospace" },
      },
      fontSizes: {
        xs: { value: '0.75rem' },
        sm: { value: '0.875rem' },
        md: { value: '1rem' },
        lg: { value: '1.125rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '1.875rem' },
        '4xl': { value: '2.25rem' },
        '5xl': { value: '3rem' },
      },
      spacing: {
        xs: { value: '0.25rem' },
        sm: { value: '0.5rem' },
        md: { value: '1rem' },
        lg: { value: '1.5rem' },
        xl: { value: '2rem' },
        '2xl': { value: '3rem' },
        '3xl': { value: '4rem' },
      },
      radii: {
        sm: { value: '0.375rem' },
        md: { value: '0.5rem' },
        lg: { value: '0.75rem' },
        xl: { value: '1rem' },
        full: { value: '9999px' },
      },
      shadows: {
        sm: { value: '0 1px 2px rgba(0, 0, 0, 0.3)' },
        md: { value: '0 4px 6px rgba(0, 0, 0, 0.3)' },
        lg: { value: '0 10px 15px rgba(0, 0, 0, 0.4)' },
        glow: { value: '0 0 20px rgba(196, 149, 106, 0.15)' },
      },
      sizes: {
        tapTarget: { value: '44px' },
      },
    },
  },
  outdir: 'styled-system',
  jsxFramework: 'react',
});
